spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: shopping-api
  datasource:
    password: '12345'
    username: root
    url: jdbc:mysql://localhost:3306/mydb
server:
  error:
    include-stacktrace: never
    include-exception: 'false'
  port: ${PORT:0} #8082
