spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: shopping-api
  datasource:
    password: '12345'
    username: root
    url: jdbc:mysql://localhost:3306/mydb

server:
  error:
    include-stacktrace: never
    include-exception: 'false'
  port: ${PORT:0} #8082

feign:
  user-api:
    name: user-api #EcomUserApi
    url: http://localhost:8765/ecommerce/usuarios/
  product-api:
    name: product-api #EcomProductsApi
    url: http://localhost:8765/ecommerce/produtos/
  endereco-api:
    name: user-api #EcomUserApi
    url: http://localhost:8765/ecommerce/usuarios/endereco/usuario

resilience4j:
  circuitbreaker:
    instances:
      saveOrderCB:
        minimumNumberOfCalls: 4
        slidingWindowSize: 8
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slowCallDurationThreshold: 4s
        maxWaitDurationInHalfOpenState: 5s
        